blueprint:
  name: Sterowanie pompą cyrkulacji wodą
  description: Sterowanie pomopą cysrkulacj pomoą
  domain: automation
  input:
    pool_pump:
      name: Water circulation pump 
      description: A switch that controls the water circulation pump
      selector:
        entity:
          domain: switch
variables:
  var_pool_pump: !input pool_pump
trigger:

action:

mode: single